apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-logging
  namespace: monitoring
  labels:
    app: elasticsearch-logging
spec: 
  type: NodePort
  ports:
  - port: 9200
    protocol: TCP
    targetPort: db
    nodePort: 30001
  selector:
    app: elasticsearch-logging
