apiVersion: apps/v1
kind: Namespace
metadata: 
  name: test
---
apiVersion: v1
kind: Service
metadata:
  name: matrix
  namespace: test
spec:
  selector:
    app: myapp
  ports:
  - port: 5000
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: myapp
  namespace: test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zion
  namespace: test
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: myapp
      imagePullSecrets:
      - name: regcred
      containers:
      - name: zion
        image: praveendevopsnexus/app:notary-signed
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
