---
# Source: kibana/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: filebeat-kibana
  labels: 
    app: kibana
    release: "filebeat"
    heritage: Helm
spec:
  type: NodePort
  ports:
    - port: 5601
      nodePort: 30001
      protocol: TCP
      name: http
      targetPort: 5601
  selector:
    app: kibana
    release: "filebeat"
---
# Source: kibana/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebeat-kibana
  labels: 
    app: kibana
    release: "filebeat"
    heritage: Helm
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: kibana
      release: "filebeat"
  template:
    metadata:
      labels:
        app: kibana
        release: "filebeat"
      annotations:
        
    spec:
      securityContext:
        fsGroup: 1000
      volumes:
      containers:
      - name: kibana
        securityContext:
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 1000
        image: "docker.elastic.co/kibana/kibana:7.9.1"
        imagePullPolicy: "IfNotPresent"
        env:
          - name: ELASTICSEARCH_HOSTS
            value: "http://elasticsearch-master:9200"
          - name: SERVER_HOST
            value: "0.0.0.0"
          - name: NODE_OPTIONS
            value: --max-old-space-size=1800
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 3
          timeoutSeconds: 5
          exec:
            command:
              - sh
              - -c
              - readiness.kibana.sh
        ports:
        - containerPort: 5601
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 1000m
            memory: 2Gi
        volumeMounts:

