apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: monitoring
  labels:
    app: "filebeat"
data:
  eshostname: elasticsearch-logging.monitoring
  esusername: elastic
  logstash_host: filebeat-logstash-headless.monitoring
  filebeat.yml: |
    filebeat.inputs:
    - type: container
      paths:
        - /var/log/containers/*.log
      processors:
      - add_kubernetes_metadata:
          host: ${NODE_NAME}
          matchers:
          - logs_path:
              logs_path: "/var/log/containers/"
    filebeat.config.inputs:
      enabled: true
      path: /usr/share/filebeat/*.yml
      reload.enabled: true
      reload.period: 10s
    output.logstash:
      host: '${NODE_NAME}'
      hosts: '${LOGSTASH_HOST:5044}'