apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: elasticsearch-logging
  namespace: monitoring
  labels:
    app: elasticsearch-logging

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: elasticsearch-logging
  labels:
    app: elasticsearch-logging
rules:
- apiGroups:
  - ""
  resources:
  - "services"
  - "namespaces"
  - "endpoints"
  verbs:
  - "get"

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: monitoring
  name: elasticsearch-logging
  labels:
    app: elasticsearch-logging
subjects:
- kind: ServiceAccount
  name: elasticsearch-logging
  namespace: monitoring
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: elasticsearch-logging
  apiGroup: ""
---

apiVersion: v1
kind: ResourceQuota
metadata:
  name: pods-high
  namespace: monitoring
spec:
  hard:
    requests.cpu: "2000"
    requests.memory: 10Gi
    limits.cpu: "3000"
    limits.memory: 20Gi
    pods: "10"

